name: 'Build WASM plugin'
author: 'Miles Johnson'
description:
  'Build, optimize, and publish WASM plugins. This is primarily for the moon and proto projects.'
runs:
  using: 'node24'
  main: 'dist/index.js'
branding:
  icon: 'layers'
  color: 'red'
inputs:
  publish:
    description: 'Publish the built plugin to an OCI registry.'
    default: 'false'
    required: false
  # registry:
  #   description: 'The OCI registry host.'
  #   default: 'ghcr.io'
  namespace:
    description: 'The OCI artifact namespace. Defaults to the current organization/user.'
    required: false
outputs:
  built:
    description: 'Whether the plugins have been built or not.'
  changelog-entry:
    description: 'The changelog entry for the affected project, if it exists.'
  tagged-project:
    description: 'The project affected by a Git tag, if applicable.'
  tagged-version:
    description: 'The extracted version from a Git tag, if applicable.'
  published:
    description: 'Whether the plugins were published or not.'
  prerelease:
    description: 'Whether the extracted version is a pre-release or not.'
