name: 'Build WASM plugin'
author: 'Miles Johnson'
description:
  'Build, optimize, and prepare WASM plugins for release. This is primarily for the moon and proto
  projects.'
runs:
  using: 'node20'
  main: 'dist/index.js'
branding:
  icon: 'layers'
  color: 'red'
outputs:
  built:
    description: 'Whether the plugins have been built or not.'
  changelog-entry:
    description: 'The changelog entry, if it exists.'
  tagged-project:
    description: 'The project affected by a Git tag, if applicable.'
  tagged-version:
    description: 'The extracted version from a Git tag, if applicable.'
