name: 'Pipeline'
on:
  push:
    branches:
      - 'master'
  pull_request:
jobs:
  ci:
    name: 'CI'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-node@v6
      - run: npm install -g pnpm
      - run: pnpm install
      - run: pnpm run check
  build:
    name: 'Build'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-node@v6
      - run: npm install -g pnpm
      - run: pnpm install
      - run: pnpm run build
      - uses: ./ # self
        with:
          publish: 'true'
        env:
          TEST_AUTH: true
      - uses: ./ # self
        env:
          TEST_BINS: true
      - run: ls -lR ~/binaryen ~/wabt ~/oras
